- platform: template
  sensors:
    target_humidity:
      device_class: humidity
      friendly_name: Target Indoor Humidity
      unit_of_measurement: "%"
      value_template: >-
        {% set t = state_attr("weather.home", "temperature") | float %}
        {{ ((t / 2) + 25) | round|int }}
