automation:
  - id: sink_light_off_at_morning
    alias: Sink Light off at Morning
    trigger:
      trigger: sun
      event: sunrise
      offset: "+00:30:00"
    action:
      - action: light.turn_off
        entity_id: light.kitchen_over_sink

  - alias: Sink Light off at Night
    id: sink_light_off_at_night
    trigger:
      trigger: time
      at: "22:30:00"
    action:
      - action: light.turn_off
        entity_id: light.kitchen_over_sink

  - alias: Sink Light on in Morning
    id: sink_light_on_in_morning
    trigger:
      trigger: time
      at: "03:15:00"
    condition:
      - condition: state
        entity_id: binary_sensor.workday
        state: "on"
    action:
      - action: light.turn_on
        entity_id: light.kitchen_over_sink
        data:
          brightness: 128

  - alias: Sink Light on if House Unoccupied and Dark
    id: sink_light_on_if_house_unoccupied_and_dark
    trigger:
      trigger: sun
      event: sunset
      offset: "-00:30:00"
    condition:
      - condition: state
        entity_id: group.residents
        state: not_home
    action:
      - action: light.turn_on
        entity_id: light.kitchen_over_sink
