automation:
  - id: "garage_doors_close_when_home"
    alias: "Garage doors close when home"
    initial_state: on
    trigger:
      # If any doors have been open for more than 30 mins
      # It gets dark outside
      - platform: state
        entity_id: input_boolean.dark_outside
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.dark_outside
        state: "on"
      - condition: state 
        entity_id: binary_sensor.garage_door
        state: "on"
    action:
      # Call the announcement engine
#      - service: script.voice_announcement
#        data:
#          media_players: auto
#          sound: "police-whistle"
#          speech_message: "Garage door has been open for a while but nobody is around so I'm automaticallly closing."
      # Notification for logging
      - service: script.general_notification
        data:
          title: "Garage Doors Open!"
          message: "Garage door has been open for a while but nobody is around so I'm automaticallly closing."
          devices: "all"
          priority: "time-sensitive"
          tag: "garage-doors-open-home"
      # Close the garage door
      - service: switch.turn_on
        entity_id: switch.garage_door_control
