---
# This file bootstraps the system
# Have a look inside the Integrations and Entities folders for my config
# moving config over to packages, cleaner

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  external_url: !secret external_url
  internal_url: !secret internal_url
  
  customize: !include customize.yaml

  packages: !include_dir_named "packages"

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

  # Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

automation: !include automations.yaml
automation manual: !include_dir_merge_list automations/
script: !include scripts.yaml
script mine: !include_dir_merge_named scripts/

frontend:
  themes: !include_dir_merge_named themes/

  # Example configuration.yaml entry
# eufy:
#   username: !secret username
#   password: !secret password

wake_on_lan:

sensor:
  - platform: mqtt_room
    name: "Tracy's iPhone - BLE"
    device_id: !secret tracy_device_id
    state_topic: espresense/devices/tracy
    timeout: 5
    away_timeout: 120


### Includes ###
group: !include groups.yaml
input_boolean: !include input_boolean.yaml
#input_datetime: !include input_datetime.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
scene: !include scenes.yaml
template: !include template.yaml
