input_boolean:
  rick_phone_plugged_in:
    name: Rick Phone Plugged In
    icon: mdi:battery-charging

sensor:
  - platform: template
    sensors:
      ricks_iphone_home:
        value_template: >-
          {% if states('sensor.ricks_iphone_ssid') == "SLYFOX"  or states('sensor.ricks_iphone_ssid') == "SLYFOX_5" %}
            Home
          {% else %}
            Away
          {% endif %}
        friendly_name: 'Ricks iPhone Home (SSID = SLYFOX)'
      
automation:
  # Rick
  #
  # Rick's phone is plugged in and charging
  - id: "rick_phone_plugged_in"
    alias: "Rick's phone is plugged in"
    mode: "single"
    trigger:
      - platform: state
        entity_id: sensor.ricks_iphone_battery_state
        to: "Charging"
      - platform: state
        entity_id: sensor.ricks_iphone_battery_state
        to: "Full"
    condition:
      - condition: state
        entity_id: input_boolean.rick_phone_plugged_in
        state: "off"
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.ricks_iphone_battery_state
            state: "Charging"
          - condition: state
            entity_id: sensor.ricks_iphone_battery_state
            state: "Full"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.rick_phone_plugged_in

  - id: "rick_phone_unplugged"
    alias: "Rick's phone is unplugged"
    mode: "single"
    trigger:
      - platform: state
        entity_id: sensor.ricks_iphone_battery_state
        to: "Not Charging"
    condition:
      - condition: state
        entity_id: sensor.ricks_iphone_battery_state
        state: "Not Charging"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.rick_phone_plugged_in