- platform: template
  sensors:
    latest_backup:
      value_template: >-
        {% set found=namespace(snapshot=None,time=0) %}
        {% for snapshot in state_attr('sensor.backup_state', 'backups') %}
          {% if as_timestamp(snapshot.date) > found.time and snapshot.state == "Backed Up" %}
            {% set found.time = as_timestamp(snapshot.date) %}
            {% set found.snapshot = snapshot %}
          {% endif %}
        {% endfor %}
        {{ found.snapshot.name }}
