input_boolean:
  house_occupied:
    name: House Occupied

# Automation to detect if the house is now occupied
#
# This automation will detect if the house is occupied
# based on a few triggers and conditions
# and if it's occupied, it will update the
# input_boolean.house_occupied to be on
#
automation:
  - id: "house_occupied"
    alias: "House occupied"
    initial_state: "on"
    trigger:
      # Triggered if John, Cristina, or Guest mode
      # get turned on
      - platform: state
        entity_id:
          - input_boolean.rick_home
        to: "on"
      # Hassio reloads/starts
      - platform: event
        event_type: automation_reloaded
      - platform: homeassistant
        event: start
    condition:
      # House is current unoccupied
      - condition: state
        entity_id: input_boolean.house_occupied
        state: "off"
      # Somebody is marked as home
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.rick_home
            state: "on"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.house_occupied

# Automation to detect if the house is not occupied
#
# This automation will detect if the house is not
# occupied based on a few triggers and conditions
# and if it's empty, it will update the
# input_boolean.house_occupied to be off
#
  - id: "house_not_occupied"
    alias: "House not occupied"
    initial_state: "on"
    trigger:
      # If John, Cristina, or Guest mode turn off
      # then trigger the automation
      - platform: state
        entity_id:
          - input_boolean.rick_home
        to: "off"
      # Hassio reloads/starts
      - platform: event
        event_type: automation_reloaded
      - platform: homeassistant
        event: start
    condition:
      condition: and
      conditions:
        # We're all away
        - condition: state
          entity_id: input_boolean.rick_home
          state: "off"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.house_occupied