---
resource: https://timeapi.io/api/TimeZone/zone?timeZone=America/Chicago
sensor:
  name: dst_dates_usa_central
  unique_id: dst_dates_usa_central
  value_template: "{{ value_json.isDayLightSavingActive }}"
  json_attributes_path: "$.dstInterval"
  json_attributes:
    - dstStart
    - dstEnd
scan_interval: 21600
