resource: "https://www.ercot.com/api/1/services/read/dashboards/supply-demand.json"
scan_interval: 300

sensor:
  - name: "Ercot Current Capacity"
    unique_id: ercot_current_capacity
    icon: mdi:transmission-tower
    value_template: >-
      {% set u = value_json.lastUpdated %}
      {% set t = u.split(" ")[1] %}
      {% set i = (t.split(":")[0] | int * 12) + (t.split(":")[1] | int // 5) %}
      {{ value_json.data[i].capacity }}

  - name: "Ercot Current Demand"
    unique_id: ercot_current_demand
    icon: mdi:transmission-tower
    value_template: >-
      {% set u = value_json.lastUpdated %}
      {% set t = u.split(" ")[1] %}
      {% set i = (t.split(":")[0] | int * 12) + (t.split(":")[1] | int // 5) %}
      {{ value_json.data[i].demand }}

  - name: "Ercot Forecast Capacity Availability"
    unique_id: ercot_forecast_capacity_availability
    icon: mdi:transmission-tower
    value_template: >-
      {%set vcount = namespace(forecastpercentage1=10,forecastpercentage2 = 0) %}
      {% for x in value_json.data %}
        {% if value_json.data[loop.index0].forecast|int == 1%}                
            {%set vcount.forecastpercentage2= value_json.data[loop.index0].demand|float /value_json.data[loop.index0].available|float %}
            {%if vcount.forecastpercentage1|float > vcount.forecastpercentage2|float%}
              {%set vcount.forecastpercentage1 = vcount.forecastpercentage2 %}
            {%endif%}
        {%endif%}                             
      {%endfor%}
      {{(100-(vcount.forecastpercentage1|float*100))|round(1)}}

  - name: "Ercot Forecast Commited Availability"
    unique_id: ercot_forecast_commited_availability
    icon: mdi:transmission-tower
    value_template: >-
      {%set vcount = namespace(forecastpercentage1=10,forecastpercentage2 = 0) %}
      {% for x in value_json.data %}
        {% if value_json.data[loop.index0].forecast|int == 1%}                
            {%set vcount.forecastpercentage2= value_json.data[loop.index0].demand|float /value_json.data[loop.index0].capacity|float %}
            {%if vcount.forecastpercentage1|float > vcount.forecastpercentage2|float%}
              {%set vcount.forecastpercentage1 = vcount.forecastpercentage2 %}
            {%endif%}
        {%endif%}                                             
      {%endfor%}
      {{(100-(vcount.forecastpercentage1|float*100))|round(1)}}