resource: "https://www.ercot.com/api/1/services/read/dashboards/daily-prc.json"
scan_interval: 300
sensor:
  unique_id: ercot_status
  icon: mdi:transmission-tower
  name: Ercot Status
  value_template: "{{value_json.current_condition.state}}"
  json_attributes_path: "$.current_condition"
  json_attributes:
    - energy_level_value
    - title
    - condition_note
    - eea_level
    - prc_value