# This will enable Christmas and all related
# automations to make sure relevant automations
# are on/off during the season

group:
  christmas_lights:
    name: Christmas Lights
    entities:
      - switch.multi_use_plug_2_switch
      - switch.multi_use_outlet

input_boolean:
  christmas_season_active:
    name: Christmas Season Active
    icon: mdi:pine-tree

automation:
  - id: "christmas_enabled"
    alias: Christmas Enabled
    mode: "single"
    trigger:
      - platform: homeassistant
        event: start
      # At 2am
      - platform: time
        at: "02:00:00"
    condition:
      # Between 12/1 - 1/07
      - condition: template
        value_template: >
          {% set d = now() %}
          {{ d.month == 12 or (d.month == 1 and ( 1<= d.day <= 7)) }}
      # Boolean is disabled
      - condition: state
        entity_id: input_boolean.christmas_season_active
        state: "off"
    action:
      # Turn the script to enable the booleans and automations
      - service: input_boolean.turn_on
        entity_id: input_boolean.christmas_season_active

  - id: "christmas_disabled"
    alias: Christmas Disabled
    mode: "single"
    trigger:
      - platform: homeassistant
        event: start
      # At 2am
      - platform: time
        at: "02:00:00"
    condition:
      # Christmas Season Active boolean is ON
      - condition: state
        entity_id: input_boolean.christmas_season_active
        state: "on"
      # Between Jan 7th and before December
      - condition: template
        value_template: >
          {% set d = now() %}
          {{ (d.month == 1 and d.day > 7) or (d.month > 2 and d.month < 12) }}
    action:
      # Turn the script to DISABLE the booleans and automations
      - service: input_boolean.turn_off
        entity_id: input_boolean.christmas_season_active
