###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   10/28/2017
#   @package        :   Holidays
#   @description    :   Retrieves the holiday
###############################################################################

homeassistant:
  customize:
    sensor.holiday:
      hidden: true
      icon: mdi:beach
      friendly_name: US Holiday

###############################################################################
# Sensor updates once every 4 hours (14400 seconds) & runs 6 times in 24 hours
#
# First it checks for holiday in static section, if that doesn't exist,
# it checks in the dynamic section. If neither exists, the value will be empty
###############################################################################
sensor:
  - platform: rest
    resource: https://schleprock.duckdns.org:8123/local/json_data/holidays.json
    name: Holiday
    scan_interval: 14400
    value_template: >
      {% set today = now().month  ~ '/' ~ now().day  %}
      {% set holiday =  value_json.MAJOR_US.static[ today ] %}
      {% if holiday | trim == "" %}
        {% set today = now().strftime('%m/%d/%Y') %}
        {% set holiday =  value_json.MAJOR_US.dynamic[ today ] %}
      {% endif %}
      {{ holiday }}

###############################################################################
#                _                        _   _
#     /\        | |                      | | (_)
#    /  \  _   _| |_ ___  _ __ ___   __ _| |_ _  ___  _ __  ___
#   / /\ \| | | | __/ _ \| '_ ` _ \ / _` | __| |/ _ \| '_ \/ __|
#  / ____ \ |_| | || (_) | | | | | | (_| | |_| | (_) | | | \__ \
# /_/    \_\__,_|\__\___/|_| |_| |_|\__,_|\__|_|\___/|_| |_|___/
#
###############################################################################
automation:
  - alias: Notify Holiday State Change
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.holiday
    condition:
      - condition: template
        value_template: "{{ states('sensor.holiday') != 'unknown' }}"
      - condition: template
        value_template: "{{ states('sensor.holiday') != 'unavailable' }}"
      - condition: template
        value_template: "{{ states('sensor.holiday') | trim != '' }}"
    action:
      - service: persistent_notification.create
        data:
          message: "Today is {{ states('sensor.holiday') }}."
          title: "{{ states('sensor.holiday') }}"
#      - service: script.notify_family
#        data:
#          message: "Today is: {{states('sensor.holiday') }}"
#          notify_options:
#            - telegram
#            - tv
#            - led