automation:
  - alias: Christmas lights on before Sunset
    trigger:
      platform: sun
      event: sunset
      offset: '-00:30:00'
    condition:
      - condition: state
        entity_id: input_boolean.christmas_time
        state: 'on'
    action:
      - service: switch.turn_on
        entity_id: group.christmas_lights

  - alias: Christmas lights off at 10:00pm
    trigger:
      - platform: time
        at: '22:00:00'
    condition:
      - condition: state
        entity_id: input_boolean.christmas_time
        state: 'on'
    action:
      - service: switch.turn_off
        entity_id: group.christmas_lights