esphome:
  name: living-room-ble-presence
  friendly_name: living-room-ble-presence
  name_add_mac_suffix: false
  platformio_options:
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio
    board_upload.maximum_ram_size: 524288
  project:
    name: esphome.web
    version: '1.0'

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: arduino

psram:
  mode: octal
  speed: 80MHz
  
# Enable logging
logger:
  level: VERY_VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "BXUdcVy6Td2JLAtcwZQs93lrRs3jzXnuxNI1ZRRLhro="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Living-Room-Ble-Presence"
    password: "j01XvXMmeih1"

esp32_ble_tracker:

captive_portal:
    
binary_sensor:
  - platform: ble_presence
    mac_address: F8:C3:CC:9D:96:46
    name: "BLE - Rick's iPhone"

sensor:
  - platform: wifi_signal
    name: "BLE - WiFi Signal Sensor"
    update_interval: 60s

