esphome:
  name: button-box
  on_boot:
    priority: 600
    then:
      - wait_until:
          api.connected:
      - delay: 2s
      - logger.log: Button Box Connected to API
      - homeassistant.service:
          service: script.bb_startup
      
esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "0111cf2d0d6c3c1391d33f0ad9f9cb52"
  platform: esphome
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Button-Box Fallback Hotspot"
    password: "OfBnLpBdeQbA"

captive_portal:
    
sensor:
  - platform: dht
    model: DHT22_TYPE2
    pin: GPIO2
    temperature:
      name: "Button Box Temperature"
    humidity:
      name: "Button Box Humidity"
    update_interval: 60s
    
switch:
  - platform: gpio
    pin: GPIO12
    id: led_1
    name: "LED 1"
    icon: "mdi:gate"
    restore_mode: RESTORE_DEFAULT_OFF
    
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO13
      mode:
        input: true
        pullup: true
    id: garage_button
    name: "BB - Garage Button"
    icon: "mdi:gate"
    on_press:
      - homeassistant.service:
          service: script.bb_garage_button_pressed
      - logger.log: Button Box button pressed
      