substitutions:
  name: "retro-control-panel"
  friendly_name: retro-control-panel

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  platformio_options:
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio
    board_upload.maximum_ram_size: 524288
  project:
    name: esphome.web
    version: '1.0'
  on_boot:
    priority: 600
    then:
      - wait_until:
          api.connected:
      - delay: 2s
      - logger.log: Retro Box Connected to API
      - homeassistant.service:
          service: script.bb_startup

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: arduino

psram:
  mode: octal
  speed: 80MHz
  
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "P7DUu/y4lhnEObs/xEOsaQLRRSPJG5BG/ZOZbR1fuLQ="
  
# Allow Over-The-Air updates
ota:
  platform: esphome
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "retro-control-panel"
    password: "nduhUWwOsJLt"

bluetooth_proxy:

esp32_ble_tracker:

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

# To have a "next url" for improv serial
web_server:

switch:
  - platform: gpio
    pin: GPIO4
    id: led_1
    name: "LED 1"
    icon: "mdi:gate"
    restore_mode: RESTORE_DEFAULT_OFF
    
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO5
      mode:
        input: true
        pullup: true
    id: garage_button
    name: "BB - Garage Button"
    icon: "mdi:gate"
    on_press:
      - homeassistant.service:
          service: script.bb_garage_button_pressed
      - logger.log: Retro Box button pressed
      
sensor:
  - platform: wifi_signal
    name: "Retro Panel - WiFi Signal Sensor"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      address_0:
        name: ESP IP Address 0
      address_1:
        name: ESP IP Address 1
      address_2:
        name: ESP IP Address 2
      address_3:
        name: ESP IP Address 3
      address_4:
        name: ESP IP Address 4
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results
    dns_address:
      name: ESP DNS Address