automation:
  - id: tracys_wifi_status
    alias: "Tracy's WiFi status"
    initial_state: "on"
    trigger:
      - trigger: state
        entity_id: sensor.tracys_iphone_ssid
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ 'SLYFOX' in states('sensor.tracys_iphone_ssid') }}"
            sequence:
              - action: mqtt.publish
                data:
                  topic: location/tracys_wifi
                  payload: "home"
                  retain: true
        default:
          - action: mqtt.publish
            data:
              topic: location/tracys_wifi
              payload: "not_home"
              retain: true
