input_boolean:
  tracy_home:
    name: Tracy Home
    icon: mdi:home

automation:
  - id: "person_tracy_away"
    alias: "Person Tracy Away"
    initial_state: "on"
    trigger:
      - trigger: zone
        entity_id:
          - person.tracy_fox
          - device_tracker.tracys_iphone
        zone: zone.home
        event: leave
      - trigger: state
        entity_id:
          - person.tracy_fox
          - device_tracker.tracys_iphone
        to: "not_home"
      # HA reload or start
      - trigger: event
        event_type: automation_reloaded
      - trigger: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: input_boolean.tracy_home
        state: "on"
        # At least one sensor reports not_home
      - condition: or
        conditions:
          # Person is not_home
          - condition: state
            entity_id: person.tracy_fox
            state: "not_home"
          # Companion app is not home
          - condition: state
            entity_id: device_tracker.tracys_iphone
            state: "not_home"
    action:
      - action: script.turn_on
        entity_id: script.tracy_away

  - id: "person_tracy_home"
    alias: "Person Tracy Home"
    initial_state: "on"
    trigger:
      # tracy enters the home zone
      - trigger: zone
        entity_id:
          - person.tracy_fox
          - device_tracker.tracys_iphone
        zone: zone.home
        event: enter
      - trigger: state
        entity_id:
          - person.tracy_fox
          - device_tracker.tracys_iphone
        to: "home"
      # HA reload or start
      - trigger: event
        event_type: automation_reloaded
      - trigger: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: input_boolean.tracy_home
        state: "off"
      - condition: or
        conditions:
          # Person is home
          - condition: state
            entity_id: person.tracy_fox
            state: "home"
          # Companion app is home
          - condition: state
            entity_id: device_tracker.tracys_iphone
            state: "home"
    action:
      - action: script.turn_on
        entity_id: script.tracy_home

script:
  tracy_home:
    alias: Tracy Home
    sequence:
      # Change the input boolean to on
      - action: input_boolean.turn_on
        entity_id: input_boolean.tracy_home
      - action: script.general_notification
        data:
          title: "Person Notification"
          message: "Tracy is marked as home."
          devices: "all"
          priority: "time-sensitive"
          tag: "person_notification_tracy"

  tracy_away:
    alias: Tracy Away
    sequence:
      # Change the input boolean to on
      - action: input_boolean.turn_off
        entity_id: input_boolean.tracy_home
      - action: script.general_notification
        data:
          title: "Person Notification"
          message: "Tracy is marked as away."
          devices: "all"
          priority: "time-sensitive"
          tag: "person_notification_tracy"
